---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: yes

- name: be sure ntp is installed
  package:
    name: ntpd
    state: present
  tags: ntpd
  become: yes

- name: be sure ntp is configured
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntpd
  become: yes

- name: be sure ntp is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntpd
  become: yes