---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: yes

- name: be sure ntp is installed
  package:
    name: ntp
    state: present
  tags: ntp
  become: yes

- name: be sure ntp is configured
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp
  become: yes

- name: be sure ntp is running and enabled
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
  become: yes